[pytest]
addopts = -ra --strict-markers -n auto --dist loadscope --reruns 2 --reruns-delay 1
markers =
    smoke: smoke tests
    regression: regression tests
    e2e: end-to-end tests
    auth: authentication configuration for tests
